"""create claims table

Revision ID: 06818102b995
Revises: 97399b315733
Create Date: 2026-07-17 21:13:21.512507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06818102b995'
down_revision: Union[str, Sequence[str], None] = '97399b315733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True),
    sa.Column('procedure_code', sa.String(length=50), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductible_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('copay_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coinsurance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payer_responsibility', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('member_responsibility', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('claim_status', sa.String(length=50), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('adjudication_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_claim_status'), 'claims', ['claim_status'], unique=False)
    op.create_index(op.f('ix_claims_enrollment_id'), 'claims', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_index(op.f('ix_claims_provider_id'), 'claims', ['provider_id'], unique=False)
    op.create_index(op.f('ix_claims_service_date'), 'claims', ['service_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_service_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_provider_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_enrollment_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
