"""create health plans table

Revision ID: 0d0be04f987a
Revises: f43180c1b67d
Create Date: 2026-07-16 19:26:35.423467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0be04f987a'
down_revision: Union[str, Sequence[str], None] = 'f43180c1b67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('coverage_level', sa.String(length=50), nullable=False),
    sa.Column('annual_deductible', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('out_of_pocket_maximum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coinsurance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('primary_care_copay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('specialist_copay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_plans_coverage_level'), 'health_plans', ['coverage_level'], unique=False)
    op.create_index(op.f('ix_health_plans_is_active'), 'health_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_health_plans_plan_code'), 'health_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_health_plans_plan_name'), 'health_plans', ['plan_name'], unique=False)
    op.create_index(op.f('ix_health_plans_plan_type'), 'health_plans', ['plan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_plans_plan_type'), table_name='health_plans')
    op.drop_index(op.f('ix_health_plans_plan_name'), table_name='health_plans')
    op.drop_index(op.f('ix_health_plans_plan_code'), table_name='health_plans')
    op.drop_index(op.f('ix_health_plans_is_active'), table_name='health_plans')
    op.drop_index(op.f('ix_health_plans_coverage_level'), table_name='health_plans')
    op.drop_table('health_plans')
    # ### end Alembic commands ###
