"""add fraud alerts

Revision ID: 3caf48cbce71
Revises: db57bda7ae36
Create Date: 2026-08-13 20:31:34.556984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3caf48cbce71'
down_revision: Union[str, Sequence[str], None] = 'db57bda7ae36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_number', sa.String(length=100), nullable=False),
    sa.Column('fraud_case_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fraud_case_id'], ['fraud_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_alert_number'), 'fraud_alerts', ['alert_number'], unique=True)
    op.create_index(op.f('ix_fraud_alerts_detected_date'), 'fraud_alerts', ['detected_date'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_fraud_case_id'), 'fraud_alerts', ['fraud_case_id'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_risk_level'), 'fraud_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_source'), 'fraud_alerts', ['source'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_title'), 'fraud_alerts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_alerts_title'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_source'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_risk_level'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_fraud_case_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_detected_date'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_alert_number'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    # ### end Alembic commands ###
