"""add reimbursements

Revision ID: 71920efc4ed2
Revises: c308c14e728e
Create Date: 2026-08-11 22:28:40.244684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71920efc4ed2'
down_revision: Union[str, Sequence[str], None] = 'c308c14e728e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimbursements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reimbursement_number', sa.String(length=100), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('reimbursement_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('withholding_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recovery_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('scheduled_payment_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=150), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=50), nullable=False),
    sa.Column('reconciliation_reference', sa.String(length=150), nullable=True),
    sa.Column('reconciled_by', sa.String(length=150), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_risk_score', sa.Float(), nullable=True),
    sa.Column('ai_risk_level', sa.String(length=50), nullable=True),
    sa.Column('ai_risk_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursements_ai_risk_level'), 'reimbursements', ['ai_risk_level'], unique=False)
    op.create_index(op.f('ix_reimbursements_ai_risk_score'), 'reimbursements', ['ai_risk_score'], unique=False)
    op.create_index(op.f('ix_reimbursements_approval_status'), 'reimbursements', ['approval_status'], unique=False)
    op.create_index(op.f('ix_reimbursements_claim_id'), 'reimbursements', ['claim_id'], unique=False)
    op.create_index(op.f('ix_reimbursements_member_id'), 'reimbursements', ['member_id'], unique=False)
    op.create_index(op.f('ix_reimbursements_payment_reference'), 'reimbursements', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_reimbursements_provider_id'), 'reimbursements', ['provider_id'], unique=False)
    op.create_index(op.f('ix_reimbursements_reconciliation_status'), 'reimbursements', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_reimbursements_reimbursement_number'), 'reimbursements', ['reimbursement_number'], unique=True)
    op.create_index(op.f('ix_reimbursements_reimbursement_type'), 'reimbursements', ['reimbursement_type'], unique=False)
    op.create_index(op.f('ix_reimbursements_scheduled_payment_date'), 'reimbursements', ['scheduled_payment_date'], unique=False)
    op.create_index(op.f('ix_reimbursements_status'), 'reimbursements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimbursements_status'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_scheduled_payment_date'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_reimbursement_type'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_reimbursement_number'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_reconciliation_status'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_provider_id'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_payment_reference'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_member_id'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_claim_id'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_approval_status'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_ai_risk_score'), table_name='reimbursements')
    op.drop_index(op.f('ix_reimbursements_ai_risk_level'), table_name='reimbursements')
    op.drop_table('reimbursements')
    # ### end Alembic commands ###
