"""create underwriting applications

Revision ID: 91d12a0a67af
Revises: 06818102b995
Create Date: 2026-08-10 21:42:43.289632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d12a0a67af'
down_revision: Union[str, Sequence[str], None] = '06818102b995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underwriting_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(length=150), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_underwriter', sa.String(length=150), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_underwriting_applications_application_number'), 'underwriting_applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_underwriting_applications_assigned_underwriter'), 'underwriting_applications', ['assigned_underwriter'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_decision'), 'underwriting_applications', ['decision'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_member_id'), 'underwriting_applications', ['member_id'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_product'), 'underwriting_applications', ['product'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_risk_score'), 'underwriting_applications', ['risk_score'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_status'), 'underwriting_applications', ['status'], unique=False)
    op.create_index(op.f('ix_underwriting_applications_submitted_date'), 'underwriting_applications', ['submitted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_underwriting_applications_submitted_date'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_status'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_risk_score'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_product'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_member_id'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_decision'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_assigned_underwriter'), table_name='underwriting_applications')
    op.drop_index(op.f('ix_underwriting_applications_application_number'), table_name='underwriting_applications')
    op.drop_table('underwriting_applications')
    # ### end Alembic commands ###
