"""create enrollments table

Revision ID: 97399b315733
Revises: 0d0be04f987a
Create Date: 2026-07-16 20:08:04.323796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97399b315733'
down_revision: Union[str, Sequence[str], None] = '0d0be04f987a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('health_plan_id', sa.Uuid(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('enrollment_type', sa.String(length=50), nullable=False),
    sa.Column('relationship_to_subscriber', sa.String(length=50), nullable=False),
    sa.Column('subscriber_member_id', sa.Uuid(), nullable=True),
    sa.Column('group_number', sa.String(length=100), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('coverage_start_date', sa.Date(), nullable=False),
    sa.Column('coverage_end_date', sa.Date(), nullable=True),
    sa.Column('enrollment_status', sa.String(length=50), nullable=False),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_plan_id'], ['health_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subscriber_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_number', name='uq_enrollments_policy_number')
    )
    op.create_index(op.f('ix_enrollments_coverage_end_date'), 'enrollments', ['coverage_end_date'], unique=False)
    op.create_index(op.f('ix_enrollments_coverage_start_date'), 'enrollments', ['coverage_start_date'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_status'), 'enrollments', ['enrollment_status'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_type'), 'enrollments', ['enrollment_type'], unique=False)
    op.create_index(op.f('ix_enrollments_group_number'), 'enrollments', ['group_number'], unique=False)
    op.create_index(op.f('ix_enrollments_health_plan_id'), 'enrollments', ['health_plan_id'], unique=False)
    op.create_index(op.f('ix_enrollments_is_active'), 'enrollments', ['is_active'], unique=False)
    op.create_index(op.f('ix_enrollments_member_id'), 'enrollments', ['member_id'], unique=False)
    op.create_index(op.f('ix_enrollments_policy_number'), 'enrollments', ['policy_number'], unique=False)
    op.create_index(op.f('ix_enrollments_subscriber_member_id'), 'enrollments', ['subscriber_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_subscriber_member_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_policy_number'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_member_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_is_active'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_health_plan_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_group_number'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_type'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_coverage_start_date'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_coverage_end_date'), table_name='enrollments')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
