"""add claim intelligence

Revision ID: ba37dd83353a
Revises: 71920efc4ed2
Create Date: 2026-08-12 19:33:48.372116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba37dd83353a'
down_revision: Union[str, Sequence[str], None] = '71920efc4ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_intelligence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_risk_score', sa.Float(), nullable=True),
    sa.Column('fraud_risk_level', sa.String(length=50), nullable=True),
    sa.Column('fraud_risk_reason', sa.Text(), nullable=True),
    sa.Column('clinical_review_status', sa.String(length=50), nullable=False),
    sa.Column('clinical_review_summary', sa.Text(), nullable=True),
    sa.Column('sla_status', sa.String(length=50), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('decision_recommendation', sa.String(length=100), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', name='uq_claim_intelligence_claim_id')
    )
    op.create_index(op.f('ix_claim_intelligence_clinical_review_status'), 'claim_intelligence', ['clinical_review_status'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_decision_recommendation'), 'claim_intelligence', ['decision_recommendation'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_fraud_risk_level'), 'claim_intelligence', ['fraud_risk_level'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_fraud_risk_score'), 'claim_intelligence', ['fraud_risk_score'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_requires_manual_review'), 'claim_intelligence', ['requires_manual_review'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_sla_breached'), 'claim_intelligence', ['sla_breached'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_sla_due_at'), 'claim_intelligence', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_claim_intelligence_sla_status'), 'claim_intelligence', ['sla_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_intelligence_sla_status'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_sla_due_at'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_sla_breached'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_requires_manual_review'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_fraud_risk_score'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_fraud_risk_level'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_decision_recommendation'), table_name='claim_intelligence')
    op.drop_index(op.f('ix_claim_intelligence_clinical_review_status'), table_name='claim_intelligence')
    op.drop_table('claim_intelligence')
    # ### end Alembic commands ###
