"""add prior authorizations

Revision ID: c308c14e728e
Revises: 91d12a0a67af
Create Date: 2026-08-11 17:44:40.354890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c308c14e728e'
down_revision: Union[str, Sequence[str], None] = '91d12a0a67af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prior_authorizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('authorization_number', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=True),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_description', sa.String(length=255), nullable=True),
    sa.Column('procedure_code', sa.String(length=50), nullable=True),
    sa.Column('procedure_description', sa.String(length=255), nullable=False),
    sa.Column('requested_service_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=True),
    sa.Column('benefit_category', sa.String(length=150), nullable=True),
    sa.Column('service_covered', sa.String(length=50), nullable=True),
    sa.Column('authorization_required', sa.String(length=50), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('medical_necessity_score', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('assigned_reviewer', sa.String(length=150), nullable=True),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision', sa.String(length=100), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('information_requested', sa.Text(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.String(length=150), nullable=True),
    sa.Column('decided_by', sa.String(length=150), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prior_authorizations_ai_recommendation'), 'prior_authorizations', ['ai_recommendation'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_assigned_reviewer'), 'prior_authorizations', ['assigned_reviewer'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_authorization_number'), 'prior_authorizations', ['authorization_number'], unique=True)
    op.create_index(op.f('ix_prior_authorizations_coverage_status'), 'prior_authorizations', ['coverage_status'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_diagnosis_code'), 'prior_authorizations', ['diagnosis_code'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_enrollment_id'), 'prior_authorizations', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_final_decision'), 'prior_authorizations', ['final_decision'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_member_id'), 'prior_authorizations', ['member_id'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_priority'), 'prior_authorizations', ['priority'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_procedure_code'), 'prior_authorizations', ['procedure_code'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_provider_id'), 'prior_authorizations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_requested_service_date'), 'prior_authorizations', ['requested_service_date'], unique=False)
    op.create_index(op.f('ix_prior_authorizations_status'), 'prior_authorizations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prior_authorizations_status'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_requested_service_date'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_provider_id'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_procedure_code'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_priority'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_member_id'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_final_decision'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_enrollment_id'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_diagnosis_code'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_coverage_status'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_authorization_number'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_assigned_reviewer'), table_name='prior_authorizations')
    op.drop_index(op.f('ix_prior_authorizations_ai_recommendation'), table_name='prior_authorizations')
    op.drop_table('prior_authorizations')
    # ### end Alembic commands ###
