"""add fraud recoveries

Revision ID: c61019c5436f
Revises: 13bbe4496fa8
Create Date: 2026-08-13 21:57:51.513584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61019c5436f'
down_revision: Union[str, Sequence[str], None] = '13bbe4496fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_recoveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_number', sa.String(length=100), nullable=False),
    sa.Column('fraud_case_id', sa.Uuid(), nullable=False),
    sa.Column('recovery_type', sa.String(length=100), nullable=False),
    sa.Column('recovery_status', sa.String(length=50), nullable=False),
    sa.Column('identified_date', sa.Date(), nullable=False),
    sa.Column('target_recovery_date', sa.Date(), nullable=True),
    sa.Column('recovered_date', sa.Date(), nullable=True),
    sa.Column('identified_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recovery_owner', sa.String(length=150), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=150), nullable=True),
    sa.Column('recovery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fraud_case_id'], ['fraud_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_recoveries_counterparty'), 'fraud_recoveries', ['counterparty'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_fraud_case_id'), 'fraud_recoveries', ['fraud_case_id'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_identified_date'), 'fraud_recoveries', ['identified_date'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_recovered_date'), 'fraud_recoveries', ['recovered_date'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_recovery_number'), 'fraud_recoveries', ['recovery_number'], unique=True)
    op.create_index(op.f('ix_fraud_recoveries_recovery_owner'), 'fraud_recoveries', ['recovery_owner'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_recovery_status'), 'fraud_recoveries', ['recovery_status'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_recovery_type'), 'fraud_recoveries', ['recovery_type'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_reference_number'), 'fraud_recoveries', ['reference_number'], unique=False)
    op.create_index(op.f('ix_fraud_recoveries_target_recovery_date'), 'fraud_recoveries', ['target_recovery_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_recoveries_target_recovery_date'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_reference_number'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_recovery_type'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_recovery_status'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_recovery_owner'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_recovery_number'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_recovered_date'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_identified_date'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_fraud_case_id'), table_name='fraud_recoveries')
    op.drop_index(op.f('ix_fraud_recoveries_counterparty'), table_name='fraud_recoveries')
    op.drop_table('fraud_recoveries')
    # ### end Alembic commands ###
