"""add policies

Revision ID: d1de10fcde0d
Revises: ba37dd83353a
Create Date: 2026-08-13 16:37:29.044707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1de10fcde0d'
down_revision: Union[str, Sequence[str], None] = 'ba37dd83353a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policyholder_member_id', sa.Uuid(), nullable=False),
    sa.Column('health_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('network_name', sa.String(length=255), nullable=True),
    sa.Column('annual_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductible_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('copay_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coinsurance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('out_of_pocket_maximum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('premium_currency', sa.String(length=10), nullable=False),
    sa.Column('billing_frequency', sa.String(length=50), nullable=False),
    sa.Column('billing_status', sa.String(length=50), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('benefits_summary', sa.Text(), nullable=True),
    sa.Column('exclusions_summary', sa.Text(), nullable=True),
    sa.Column('renewal_eligible', sa.Boolean(), nullable=False),
    sa.Column('renewal_due_date', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_plan_id'], ['health_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policyholder_member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_billing_status'), 'policies', ['billing_status'], unique=False)
    op.create_index(op.f('ix_policies_effective_date'), 'policies', ['effective_date'], unique=False)
    op.create_index(op.f('ix_policies_expiry_date'), 'policies', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_policies_health_plan_id'), 'policies', ['health_plan_id'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_next_payment_date'), 'policies', ['next_payment_date'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_policies_policyholder_member_id'), 'policies', ['policyholder_member_id'], unique=False)
    op.create_index(op.f('ix_policies_renewal_due_date'), 'policies', ['renewal_due_date'], unique=False)
    op.create_index(op.f('ix_policies_renewal_eligible'), 'policies', ['renewal_eligible'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_renewal_eligible'), table_name='policies')
    op.drop_index(op.f('ix_policies_renewal_due_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_policyholder_member_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_next_payment_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_health_plan_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_expiry_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_effective_date'), table_name='policies')
    op.drop_index(op.f('ix_policies_billing_status'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
