"""add fraud investigator notes

Revision ID: eee14f7120d0
Revises: 14b424f8a770
Create Date: 2026-08-13 21:10:20.891307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee14f7120d0'
down_revision: Union[str, Sequence[str], None] = '14b424f8a770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_investigator_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('note_number', sa.String(length=100), nullable=False),
    sa.Column('fraud_case_id', sa.Uuid(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('author_role', sa.String(length=150), nullable=True),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fraud_case_id'], ['fraud_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_investigator_notes_author'), 'fraud_investigator_notes', ['author'], unique=False)
    op.create_index(op.f('ix_fraud_investigator_notes_fraud_case_id'), 'fraud_investigator_notes', ['fraud_case_id'], unique=False)
    op.create_index(op.f('ix_fraud_investigator_notes_note_date'), 'fraud_investigator_notes', ['note_date'], unique=False)
    op.create_index(op.f('ix_fraud_investigator_notes_note_number'), 'fraud_investigator_notes', ['note_number'], unique=True)
    op.create_index(op.f('ix_fraud_investigator_notes_visibility'), 'fraud_investigator_notes', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_investigator_notes_visibility'), table_name='fraud_investigator_notes')
    op.drop_index(op.f('ix_fraud_investigator_notes_note_number'), table_name='fraud_investigator_notes')
    op.drop_index(op.f('ix_fraud_investigator_notes_note_date'), table_name='fraud_investigator_notes')
    op.drop_index(op.f('ix_fraud_investigator_notes_fraud_case_id'), table_name='fraud_investigator_notes')
    op.drop_index(op.f('ix_fraud_investigator_notes_author'), table_name='fraud_investigator_notes')
    op.drop_table('fraud_investigator_notes')
    # ### end Alembic commands ###
